name: Build WearGPT APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant permission to Gradle
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        run: |
          mkdir -p upload
          cp app/build/outputs/apk/debug/app-debug.apk upload/
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WearGPT-APK
          path: upload/app-debug.apk
